Repository ohreteam/ohre, pull requests merged in 2025-02, with the labels that each got.

#14 more TAC, val conflict supported in get_all_prev_cbs_var2val
  .gitignore
  examples/dis_demo.py
  ohre/abcre/dis/AsmArg.py
  ohre/abcre/dis/AsmMethod.py
  ohre/abcre/dis/AsmRecord.py
  ohre/abcre/dis/AsmString.py
  ohre/abcre/dis/CodeBlock.py
  ohre/abcre/dis/CodeBlocks.py
  ohre/abcre/dis/ControlFlow.py
  ohre/abcre/dis/DebugBase.py
  ohre/abcre/dis/DisFile.py
  ohre/abcre/dis/NAC.py
  ohre/abcre/dis/NACtoTAC.py
  ohre/abcre/dis/PandaReverser.py
  ohre/abcre/dis/TAC.py
  ohre/abcre/dis/enum/NACTYPE.py
  ohre/abcre/dis/lifting/CopyPropagation.py
  ohre/abcre/dis/lifting/DeadCodeElimination.py
  ohre/abcre/dis/lifting/PeepholeOptimization.py
  ohre/misc/Log.py
  ohre/misc/utils.py
Labels: bug, enhancement

#17 lexenv tac lifting
  ohre/abcre/dis/AsmArg.py
  ohre/abcre/dis/AsmLiteral.py
  ohre/abcre/dis/NACtoTAC.py
Labels: enhancement

#18 fix, ModuleVarAnalysis, global var in module start
  examples/dis_demo.py
  ohre/abcre/dis/AsmArg.py
  ohre/abcre/dis/DisFile.py
  ohre/abcre/dis/PandaReverser.py
  ohre/abcre/dis/TAC.py
  ohre/abcre/dis/enum/CODE_LV.py
  ohre/abcre/dis/lifting/CopyPropagation.py
  ohre/abcre/dis/lifting/ModuleVarAnalysis.py
Labels: bug, enhancement

#19 tac builders, DCE add, local module load support
  .gitignore
  examples/dis_demo.py
  ohre/abcre/dis/AsmArg.py
  ohre/abcre/dis/AsmLiteral.py
  ohre/abcre/dis/AsmMethod.py
  ohre/abcre/dis/AsmRecord.py
  ohre/abcre/dis/CodeBlock.py
  ohre/abcre/dis/DisFile.py
  ohre/abcre/dis/NAC.py
  ohre/abcre/dis/NACtoTAC.py
  ohre/abcre/dis/PandaReverser.py
  ohre/abcre/dis/TAC.py
  ohre/abcre/dis/enum/AsmTypes.py
  ohre/abcre/dis/lifting/CopyPropagation.py
  ohre/abcre/dis/lifting/DeadCodeElimination.py
  ohre/abcre/dis/lifting/PeepholeOptimization.py
  ohre/misc/utils.py
Labels: bug, enhancement

#20 performance optimization, tac builders
  .gitignore
  examples/dis_demo.py
  ohre/abcre/dis/AsmArg.py
  ohre/abcre/dis/AsmLiteral.py
  ohre/abcre/dis/AsmMethod.py
  ohre/abcre/dis/AsmRecord.py
  ohre/abcre/dis/CodeBlock.py
  ohre/abcre/dis/ControlFlow.py
  ohre/abcre/dis/DisFile.py
  ohre/abcre/dis/ISA.py
  ohre/abcre/dis/NACtoTAC.py
  ohre/abcre/dis/PandaReverser.py
  ohre/abcre/dis/TAC.py
  ohre/abcre/dis/enum/AsmTypes.py
  ohre/abcre/dis/enum/NACTYPE.py
  ohre/abcre/dis/lifting/CopyPropagation.py
  ohre/abcre/dis/lifting/DeadCodeElimination.py
  ohre/abcre/dis/lifting/LivingVar.py
  ohre/abcre/dis/lifting/ModuleVarAnalysis.py
  ohre/abcre/dis/lifting/PeepholeOptimization.py
  ohre/misc/Log.py
Labels: bug, enhancement

#21 Module info start
  examples/dis_demo.py
  ohre/abcre/dis/AsmMethod.py
  ohre/abcre/dis/DisFile.py
  ohre/abcre/dis/ModuleInfo.py
  ohre/abcre/dis/NACtoTAC.py
  ohre/abcre/dis/PandaReverser.py
  ohre/abcre/dis/TAC.py
  ohre/abcre/dis/lifting/CopyPropagation.py
  ohre/abcre/dis/lifting/DeadCodeElimination.py
  ohre/abcre/dis/lifting/ModuleVarAnalysis.py
  ohre/abcre/dis/lifting/PeepholeOptimization.py
Labels: enhancement

#23 trackbug
  .gitignore
  README.md
  examples/dis_demo.py
  ohre/abcre/dis/AsmArg.py
  ohre/abcre/dis/AsmLiteral.py
  ohre/abcre/dis/AsmMethod.py
  ohre/abcre/dis/AsmRecord.py
  ohre/abcre/dis/AsmString.py
  ohre/abcre/dis/AsmTypes.py
  ohre/abcre/dis/CodeBlock.py
  ohre/abcre/dis/CodeBlocks.py
  ohre/abcre/dis/ControlFlow.py
  ohre/abcre/dis/DebugBase.py
  ohre/abcre/dis/DisFile.py
  ohre/abcre/dis/ISA.py
  ohre/abcre/dis/ModuleInfo.py
  ohre/abcre/dis/NAC.py
  ohre/abcre/dis/NACtoTAC.py
  ohre/abcre/dis/PandaReverser.py
  ohre/abcre/dis/TAC.py
  ohre/abcre/dis/TACTYPE.py
  ohre/abcre/dis/enum/AsmTypes.py
  ohre/abcre/dis/enum/CODE_LV.py
  ohre/abcre/dis/enum/NACTYPE.py
  ohre/abcre/dis/enum/TACTYPE.py
  ohre/abcre/dis/lifting/CopyPropagation.py
  ohre/abcre/dis/lifting/DeadCodeElimination.py
  ohre/abcre/dis/lifting/LivingVar.py
  ohre/abcre/dis/lifting/ModuleVarAnalysis.py
  ohre/abcre/dis/lifting/PeepholeOptimization.py
  ohre/misc/Log.py
  ohre/misc/utils.py
Labels: bug
